function y = tsFun(par)
% Interpretaion of time-series analysis. The time series generated by the
% groundwater model is fast, as its head increase follows immediately after
% recharge. Also, it has no noise. Therefore, we can model it with an
% impulse response that is an exponential decay.
global PE head

ymean = par(1);
mu    = exp(par(2));
tau0  = exp(par(3));

IR = 1/mu * exp(-(1:1000)/tau0);

y = filter(IR,1,PE)+ymean - head;

fprintf('.');
